### ISSUE TITLE
Do have an approximate time plan for this proposal?

### ISSUE THREAD

**Issue by wangfakang** [WebAssembly/stack-switching#1]
Thank you for your contribution to this proposal. May I ask if there is a approximate time plan for this proposal? thx.

**Comment by tlively** [comment]
The proposal advanced to phase 2 today and the champions have shared a goal of getting it to phase 3 in early 2025. Beyond that, it will heavily depend on the feedback we get from users and the availability of engineering resources to productionize the implementation in two Web browsers.

Since it's not really possible to be more specific than that, I'll go ahead an close this issue, but feel free to reopen it if there are follow-on questions.
