### ISSUE TITLE
Function coloring?

### ISSUE THREAD

**Issue by pannous** [WebAssembly/stack-switching#42]
Does this approach avoid function coloring? That is: do legacy calls of functions containing yield instructions just treat these as nop?

**Comment by rossberg** [comment]
Neither. We definitely don't want function coloring, i.e, a static effect system. But stack switching does not need that. In all variants of the proposal circulated so far switching stacks works without static knowledge of such effects. In fact, that is a main point of the proposal, because in the presence of such knowledge, you can already implement the equivalent semantics producer-side, e.g., through partial CPS conversions, or the approach taken by Asyncify.

**Comment by dead-claudia** [comment]
> Does this approach avoid function coloring? That is: do legacy calls of functions containing yield instructions just treat these as nop?

@pannous For a simpler answer: It's based on (a variant of) continuations. Continuations color runtime contexts, not functions.

As for `suspend` outside a typed continuation, it would trap at rumtime.

**Comment by tlively** [comment]
Closing this as answered, but feel free to reopen if there are follow-up questions.
