### ISSUE TITLE
Linear time checks in bag-o-stacks

### ISSUE THREAD

**Issue by tlively** [WebAssembly/stack-switching#60]
In https://github.com/WebAssembly/stack-switching/issues/59#issuecomment-2143355885 @rossberg wrote,

> Plus, if you also have undirected (symmetric) switches, like with bag-o-stacks, then those have to perform the linear check every time, because they lack the structure to establish additional invariants. That is, you'll end having to check twice as often as when using asymmetric primitives.

I am not under the impression that bag-o-stacks requires any linear checks. When switching stacks, it’s only necessary to check whether the target is valid (using sequence numbers), and whether the current stack contains a host frame (implementable using one counter per stack incremented when calling from JS to Wasm).

My understanding is that we pay for the benefit of having no linear checks by being less expressive (see https://github.com/WebAssembly/stack-switching/issues/49#issuecomment-2103441181).

Am I missing something, @rossberg?

**Comment by slindley** [comment]
I'm fairly sure that all that @rossberg is saying here is that if you try to recover the missing expressiveness of wasmfx by simulating it (or something like it) on top of bag-o-stacks - e.g. by using an approach similar to the one you sketched recently in your stacks group talk about bag-o-stacks - then you inevitably do pay a linear cost, and because you're doing a simulation the constant factors will compound that cost.

**Comment by rossberg** [comment]
@tlively, what I'm saying is that as soon as you merely add something like the stack.link instruction, as you suggested for bag-of-stacks, *every* switch, even symmetric ones, will require a linear check. I don't see how you can guarantee to preserve well-formedness of stack chains otherwise.

As far as I'm concerned, the whole linear-check question is more or less a red herring. Any sufficiently expressive system will need it. And that's fine, in practice handlers don't need to be nested deeply enough for it to matter.

**Comment by tlively** [comment]
Got it, thanks. `stack.link` is not included in the bag-o-stacks proposal, so on its own it has no linear time operations. Of course Sam is right that using it to emulate WasmFX leads to linear search in user space, though.

I agree that the presence of linear time operations may not end up being important.

**Comment by rossberg** [comment]
> `stack.link` is not included in the bag-o-stacks proposal, so on its own it has no linear time operations. 

That's correct, but of course that also means that it is not possible to extend it later or complement it with features to become sufficiently expressive without destroying a primary selling point.
